// 30-day scenario images (middle-male). Usage: node images3.mjs [names...]
import fs from 'node:fs/promises';
import path from 'node:path';
const API = 'https://api.openai.com/v1/images/generations';
const KEY = process.env.OPENAI_API_KEY;
const OUT = path.join(import.meta.dirname, 'images');
const Q = `\n\n— Style: premium Japanese recruitment/career-service LINE banner, square 1024x1024. Palette: deep navy (#0f2a4a), white, champagne gold accents, light grey cards. Target audience: Japanese men aged 25-34 in physically demanding or quota-driven jobs who want a weekday office job with weekends off. Photos (if any): realistic Japanese man around 28-33, short black hair, calm confident expression, office or casual-business look, no model-like smile. Typography: bold modern Gothic, high legibility, tidy layout with generous margins. Render EVERY Japanese character perfectly correct and clean (no garbled/fake glyphs). No English paragraph text, no watermark, no logos except a small text mark 「ハックツ就職」 at top-left. Include EXACTLY the text listed and nothing else. Professional, trustworthy, masculine, not cute, no pink.`;
const J = {
d01_hikoukai: `Explanatory banner, no photo. Top: mark 「ハックツ就職」, headline navy 「非公開求人がネットに出ない理由」. Middle: a simple flow diagram: a navy building icon 「企業」 with two arrows; the top arrow to a grey crossed-out globe 「求人サイト」 with grey note 「応募殺到・年齢層のミスマッチ」; the bottom arrow to a gold building icon 「エージェント」 with gold note 「条件に合う人だけに紹介」. Below: a large gold stat 「7割」 with text 「「未経験可・年収500万以上」の求人は7割が非公開」. Bottom: big rounded navy button 「非公開求人を紹介してもらう ▶」.`,
d02_age: `Data banner, no photo. Top: mark 「ハックツ就職」, small grey label 「当社紹介求人ベース（25〜29歳=100）」, headline navy 「未経験可求人の年齢分布」. Middle: four horizontal bars on white, labels left, values right: 「25〜29歳」 bar full length gold 「100」; 「30〜34歳」 bar 68% navy 「68」; 「35〜39歳」 bar 31% grey 「31」; 「40歳〜」 bar 12% grey 「12」. A gold vertical dashed line between the 2nd and 3rd bars with tag 「34歳が分かれ目」. Bottom: big rounded navy button 「今の年齢で狙える求人を見る ▶」.`,
d03_jirei_saas: `Case-study banner with a small round photo of a Japanese man around 32 in a navy jacket at top-left of the card. Top: mark 「ハックツ就職」, gold ribbon 「内定事例」, headline navy 「32歳 施工管理 → SaaS法人営業」. Middle: a stepped bar chart of monthly pay over 12 months on white: 「1〜3ヶ月」 bar 「35万」 (grey, note 「研修期間」), 「4〜6ヶ月」 bar 「42万」 (navy), 「7〜12ヶ月」 bar 「50万＋賞与」 (gold). Below: three white pills with gold checks 「年収420万→600万」「土日祝休み」「残業 月8h」. Bottom: big rounded navy button 「自分の場合を診断する ▶」. Tiny footnote 「※実績は一例です」.`,
d04_week: `Comparison banner, no photo. Top: mark 「ハックツ就職」, headline navy 「土日祝休みで変わる1週間」. Two weekly calendars side by side, Mon–Sun columns 「月火水木金土日」. Left card (grey header 「今：シフト制」): Mon–Sat cells filled grey with 「出勤」 and small text 「帰宅22時」, Sun cell 「休」. Right card (navy header with gold 「転職後」): Mon–Fri cells navy 「9:30-18:30」, Sat and Sun cells gold 「休」, and a small gold note under Mon–Fri 「平日夜はジム・自分の時間」. Bottom: big rounded navy button 「この働き方の求人を見る ▶」.`,
d05_5years: `Data banner, no photo. Top: mark 「ハックツ就職」, headline navy 「転職しない場合の5年後」. Middle: a line chart on white with x-axis 「今」「1年後」「2年後」「3年後」「4年後」「5年後」. Grey line labeled 「今のまま」 nearly flat: 380万→390万→400万→400万→400万. Gold line labeled 「転職した場合」 rising: 380万→480万→540万→600万→650万. Endpoints labeled 「400万」 (grey) and 「650万」 (gold). Below the chart a navy strip with white text 「5年間の累計差 約600万円」. Bottom: big rounded gold button with navy text 「5年後の年収を診断する ▶」.`,
d06_uchiwake: `Data banner, no photo. Top: mark 「ハックツ就職」, small grey label 「SaaS法人営業の例」, headline navy 「年収600万の内訳」. Middle: a stacked horizontal bar or three stacked rows on white: 「基本給」「32万×12ヶ月」「384万」 (navy), 「インセンティブ」「月平均8万×12ヶ月」「96万」 (gold), 「賞与」「年3回」「120万」 (light navy); total row 「合計」「600万」 in large gold. Below: a light grey box with gold check 「新規飛び込みではなく既存提案が中心。インセンティブが安定」. Bottom: big rounded navy button 「内訳を詳しく聞く ▶」.`,
d08_saas_day: `Timeline banner with a small photo strip at right of a Japanese man around 30 on a laptop video call. Top: mark 「ハックツ就職」, headline navy 「SaaS法人営業の1日」. Vertical timeline with gold dots and times in navy: 「9:30」「出社・メール確認」 / 「10:00」「既存顧客とオンライン商談」 / 「12:00」「昼休み」 / 「13:00」「提案資料の作成」 / 「15:00」「商談2件」 / 「17:30」「日報」 / 「18:30」「退社」. Below: navy strip white text 「飛び込み・テレアポなし」. Bottom: big rounded navy button 「この職種の求人を見る ▶」.`,
d09_jinji_day: `Timeline banner, small photo at right of a Japanese man around 34 at an office desk. Top: mark 「ハックツ就職」, gold tag 「34歳・元飲食店長」, headline navy 「人事・採用担当の1日」. Vertical timeline gold dots: 「9:00」「応募者への連絡」 / 「10:30」「面接の日程調整」 / 「13:00」「面接に同席」 / 「15:00」「求人票の作成」 / 「17:00」「定時退社」. Below: navy strip white text 「立ち仕事から内勤へ。土日祝休み」. Bottom: big rounded navy button 「この職種の求人を見る ▶」.`,
d10_it_career: `Data banner, no photo. Top: mark 「ハックツ就職」, headline navy 「ITインフラは年次で年収が積み上がる」. Middle: a rising step chart of four gold-topped navy bars: 「1年目」「480万」 note 「未経験入社・資格取得支援」; 「2年目」「560万」 note 「CCNA / LinuC 取得」; 「3年目」「620万」 note 「設計を担当」; 「5年目」「700万〜」. Below: light grey box with gold check 「体力ではなくスキルで上がる」. Bottom: big rounded navy button 「ITインフラの求人を見る ▶」.`,
d11_kikaku_sns: `Explanatory banner, no photo. Top: mark 「ハックツ就職」, headline navy 「ノルマ営業の経験は、企画・マーケで武器になる」. Middle: three white cards in a row with gold icons: 「数字を追う習慣」「顧客の反応を見る力」「締切を守る力」. A gold arrow down to two navy cards: 「事業企画・営業企画」「年収620万〜」 and 「SNSマーケティング職」「年収580万〜」. Below: navy strip white text 「追うのがノルマからKPIに変わるだけ」. Bottom: big rounded navy button 「企画・マーケの求人を見る ▶」.`,
d12_faq2: `FAQ banner, no photo. Top: mark 「ハックツ就職」, headline navy 「よくある質問 第2弾」. Four white cards each with a gold circle 「Q」 and navy circle 「A」:
Q「家族に反対されている」 A「年収・休日の変化を数字で示す資料を面談で作ります」
Q「貯金がなく転職期間が不安」 A「在職中に内定まで進めるので無収入の期間はゼロ」
Q「転職回数が多い」 A「3回までなら未経験可求人の大半が対象です」
Q「地方在住」 A「リモート可・転勤なしの求人を優先して紹介」
Bottom: big rounded navy button 「他の不安も相談する ▶」.`,
d13_genba: `Explanatory banner with a small photo of a Japanese man around 30 in work clothes looking forward, at right. Top: mark 「ハックツ就職」, headline navy 「現場経験は、評価されます」, gold sub 「採用側が見る3点」. Three numbered white cards with gold numbers: 「1」「体力仕事を続けた継続力」 / 「2」「現場で客と向き合った対人力」 / 「3」「シフト勤務の自己管理」. Below: navy strip white text 「未経験＝ゼロではありません」. Bottom: big rounded navy button 「自分の経験の評価を聞く ▶」.`,
d14_shimekiri: `Urgency banner, premium and calm, no photo, NO calendar. Top: mark 「ハックツ就職」, gold ribbon 「今月の相談受付について」. Headline white on navy 「「未経験可・年収500万以上」は月末で締まります」. Middle: two white cards with gold checks: 「多くの企業が月末で募集を締め、翌月は条件が変わります」「今月中に面談した方から順に紹介しています」. Bottom: big rounded gold button with navy text 「今月分の面談枠を確保する ▶」.`,
d15_zaishoku: `Step banner, no photo. Top: mark 「ハックツ就職」, headline navy 「在職中に転職活動を進める手順」. Four numbered steps in white cards with navy circles: 「1」「LINEで面談（夜・土日OK）」 / 「2」「エージェント3社が求人を提案」 / 「3」「面接は有給または夜のオンライン」 / 「4」「内定後に退職を伝える」. Below: navy strip white text 「会社に知られるルートはありません」. Bottom: big rounded navy button 「在職中のまま相談する ▶」.`,
d16_mendan3: `Simple banner, no photo. Top: mark 「ハックツ就職」, headline navy 「面談で聞かれるのは3つだけ」. Three large white cards with gold numbers: 「1」「今の仕事と年収」 / 「2」「譲れない条件（休日・年収・勤務地）」 / 「3」「いつまでに動きたいか」. Below: light grey box with gold checks 「履歴書・職務経歴書は不要」「準備ゼロで20分」. Bottom: big rounded navy button 「20分の面談を予約する ▶」.`,
d17_3sha_jirei: `Case-study banner, no photo. Top: mark 「ハックツ就職」, gold tag 「3社紹介の実例」, headline navy 「31歳 男性・製造職の場合」. Three navy cards in a row: 「A社 IT特化」「ITインフラ 2件」 / 「B社 営業特化」「SaaS営業 3件」 / 「C社 総合」「人事 1件」. A gold arrow down to a white result card: 「計6件から比較 → SaaS営業に決定」「年収400万 → 580万」. Below: navy strip white text 「1社だけなら選択肢は2件でした」. Bottom: big rounded gold button navy text 「自分に合う3社を紹介してもらう ▶」.`,
d19_koushou: `Comparison banner, no photo. Top: mark 「ハックツ就職」, headline navy 「年収交渉はエージェントが代行」. Two cards: left grey header 「自分で交渉」 with grey text 「提示額のまま」 and a flat grey bar; right navy header gold text 「エージェント経由」 with a large gold stat 「平均 +91.3万円」 and a taller gold bar. Below: light grey box gold check 「未経験入社でも交渉の余地はあります」. Bottom: big rounded navy button 「交渉込みで求人を紹介してもらう ▶」.`,
d20_jirei_it: `Case-study banner with a small round photo of a Japanese man around 29 in a casual shirt. Top: mark 「ハックツ就職」, gold ribbon 「内定事例」, headline navy 「29歳 配送ドライバー → ITインフラエンジニア」. Middle: two gold-topped navy bars 「1年目」「480万」 note 「資格2つ取得（会社負担）」 and 「2年目」「560万」. Three white pills with gold checks: 「残業 月10h」「リモート 週2」「土日祝休み」. A quote line in navy 「体力で稼ぐ働き方に限界を感じて転職しました」. Bottom: big rounded navy button 「自分の場合を診断する ▶」.`,
d21_jiki: `Data banner, no photo. Top: mark 「ハックツ就職」, headline navy 「未経験採用が動く時期」. Middle: a bar chart of four quarters on white: 「1〜3月」 tall gold bar 「多」, 「4〜6月」 medium navy 「中」, 「7〜9月」 tall gold 「多」, 「10〜12月」 medium navy 「中」, y-axis label 「求人数」. Below: light grey box gold check 「求人が多い時期に面談を済ませておくと、選べる求人が増えます」. Bottom: big rounded navy button 「今の求人状況を聞く ▶」.`,
d22_10years: `Comparison banner, no photo. Top: mark 「ハックツ就職」, headline navy 「10年後の比較」. Two columns: left grey header 「体力で稼ぐ」 with three grey-x lines 「年収は横ばい」「身体の負担が増える」「40代で選択肢が減る」; right navy header gold text 「スキルで稼ぐ」 with three gold-check lines 「年収が積み上がる」「内勤で長く働ける」「40代でも転職できる」. Below: navy strip white text 「分かれ道は34歳まで」. Bottom: big rounded gold button navy text 「10年後を変える相談をする ▶」.`,
};
const targets = process.argv.slice(2).length ? process.argv.slice(2) : Object.keys(J);
for (const name of targets) {
  const prompt = J[name] + Q; if (!J[name]) { console.warn('skip', name); continue; }
  console.log('→', name);
  for (let a = 1; a <= 2; a++) {
    const res = await fetch(API, { method: 'POST', headers: { Authorization: `Bearer ${KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: 'gpt-image-2', prompt, size: '1024x1024', n: 1 }) });
    if (!res.ok) { console.error('  FAIL', res.status, (await res.text()).slice(0, 200)); continue; }
    const d = await res.json();
    await fs.writeFile(path.join(OUT, `${name}.png`), Buffer.from(d.data[0].b64_json, 'base64'));
    console.log('  ✓', name); break;
  }
}
console.log('done.');
